const types = {
  CHANGE_TABS: "CHANGE_TABS",
  CHANGE_NAV: "CHANGE_NAV",
  FETCH_TEAMS: "FETCH_TEAMS",
  UPDATE_FAVORITE: "UPDATE_FAVORITE",
  UPDATE_TEAM_SEARCH: " UPDATE_TEAM_SERACH",
};
export default types;
